replicaCount: 1

image:
  tag: 1.0.0
  repository: jrmcdonald/ifsc-ical-generator
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - host: ifsc.qwyck-cloud.co.uk
      paths: ["/"]
  tls:
    - secretName: ifsc-ical-generator-tls
      hosts:
        - ifsc.qwyck-cloud.co.uk

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

probes:
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 3
    failureThreshold: 15

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

applicationConfig:
  external:
    ifsc:
      host: "http://egw.ifsc-climbing.org"
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
