replicaCount: 1

image:
  tag: 1.0.0
  repository: jrmcdonald/ifsc-ical-generator
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /actuator {
        deny all;
        return 403;
      }
  hosts:
    - host: api.qwyck-cloud.co.uk
      paths: ["/ifsc"]
  tls:
    - secretName: api-qwyck-cloud-tls
      hosts:
        - api.qwyck-cloud.co.uk

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

probes:
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 3
    failureThreshold: 15

resources:
  limits:
    cpu: 100m
    memory: 400M
  requests:
    cpu: 100m
    memory: 400M

nodeSelector: {}

tolerations: []

affinity: {}

applicationConfig:
  external:
    ifsc:
      host: "http://egw.ifsc-climbing.org"
  management:
    endpoint:
      restart:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,info,metrics,restart
  server:
    servlet:
      contextPath: /ifsc
  spring:
    cloud:
      kubernetes:
        reload:
          strategy: restart_context
