apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "techbyte-demo.fullname" . }}
  labels:
  {{- include "techbyte-demo.labels" . | nindent 4 }}
data:
  application.yml: |-
  {{- toYaml .Values.applicationConfig | nindent 4 }}