apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "techbyte-demo.fullname" . }}
  labels:
  {{- include "techbyte-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "techbyte-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "techbyte-demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "techbyte-demo.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
          {{- toYaml .Values.probes.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.probes.readinessProbe | nindent 12 }}
          startupProbe:
          {{- toYaml .Values.probes.startupProbe | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.secrets.mountNamedSecret }}
          volumeMounts:
            - mountPath: /etc/secrets/{{ include "techbyte-demo.fullname" . }}
              name: {{ include "techbyte-demo.fullname" . }}
              readOnly: true
          {{- end }}
      {{- if .Values.secrets.mountNamedSecret }}
      volumes:
        - name: {{ include "techbyte-demo.fullname" . }}
          secret:
            secretName: {{ include "techbyte-demo.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
