apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "techbyte-demo.fullname" . }}
  labels:
  {{- include "techbyte-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "techbyte-demo.selectorLabels" . | nindent 4 }}
