---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ms-customer-entity
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:^1.0.0
spec:
  releaseName: ms-customer-entity
  chart:
    git: git@github.com:jrmcdonald/helm-charts
    path: charts/ms-customer-entity
    ref: main
  values:
    image:
      repository: jrmcdonald/ms-customer-entity
      tag: 1.3.0
