replicaCount: 1

image:
  tag: 1.0.0
  repository: jrmcdonald/ms-openapi-gateway
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ambassador:
  enabled: true
  prefix: /openapi-gateway/
  rewrite: /

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

secrets:
  mountNamedSecret: false

probes:
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 3
    failureThreshold: 8

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

applicationConfig:
  management:
    endpoint:
      restart:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus,restart
  spring:
    cloud:
      kubernetes:
        reload:
          strategy: restart_context
  openapi:
    endpoints:
      customer-orchestration:
        gateway-prefix: /openapi-gateway
        service-url: http://ms-customer-orchestration.prod
        service-prefix: /customer-orchestration
        service-path: /v3/api-docs
      customer-entity:
        gateway-prefix: /openapi-gateway
        service-url: http://ms-customer-entity.prod
        service-prefix: /customer-entity
        service-path: /v3/api-docs
  springdoc:
    swagger-ui:
      path: /
      config-url: /openapi-gateway/swagger-config.json
    webjars:
      prefix: /openapi-gateway/webjars
