{{- if .Values.ambassador.enabled -}}
  {{- range $key, $mapping := .Values.ambassador.mappings }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ printf "%s-%s" (include "<CHARTNAME>.fullname" $) $key }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  {{- toYaml $mapping | nindent 4 }}
    {{- end }}
    {{- end }}