apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
  {{- include "<CHARTNAME>.labels" . | nindent 4 }}
data:
  application.yml: |-
  {{- toYaml .Values.applicationConfig | nindent 4 }}