apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "ms-customer-orchestration.fullname" . }}
  labels:
  {{- include "ms-customer-orchestration.labels" . | nindent 4 }}
data:
  application.yml: |-
  {{- toYaml .Values.applicationConfig | nindent 4 }}