{{- if .Values.ambassador.enabled -}}
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "ms-openapi-gateway.fullname" . }}
  labels:
  {{- include "ms-openapi-gateway.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.ambassador.mapping | nindent 2 }}
  {{- end }}