kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ms-openapi-gateway.fullname" . }}
  labels:
  {{- include "ms-openapi-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch", "edit", "view"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ms-openapi-gateway.fullname" . }}
  labels:
  {{- include "ms-openapi-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ms-openapi-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ms-openapi-gateway.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
