replicaCount: 1

image:
  tag: 1.0.0
  repository: jrmcdonald/ms-customer-entity
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /actuator {
        deny all;
        return 403;
      }
  hosts:
    - host: api.qwyck-cloud.co.uk
      paths: ["/customer-entity"]
  tls:
    - secretName: api-qwyck-cloud-tls
      hosts:
        - api.qwyck-cloud.co.uk

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

probes:
  livenessProbe:
    httpGet:
      path: /customer-entity/actuator/health/liveness
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /customer-entity/actuator/health/readiness
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /customer-entity/actuator/health/liveness
      port: http
    periodSeconds: 3
    failureThreshold: 8

resources:
  limits:
    cpu: 100m
    memory: 400M
  requests:
    cpu: 100m
    memory: 400M

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  postgresqlUsername: customer-entity
  existingSecret: postgresql-credentials
  persistence:
    size: 4Gi
    storageClass: rook-ceph-block

applicationConfig:
  management:
    endpoint:
      restart:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus,restart
  server:
    servlet:
      contextPath: /customer-entity
  spring:
    cloud:
      kubernetes:
        reload:
          strategy: restart_context
    datasource:
      url: jdbc:postgresql://ms-customer-entity-postgresql.prod.svc.cluster.local:5432/postgres
      username: customer-entity
