replicaCount: 1

image:
  tag: 1.0.0
  repository: jrmcdonald/ms-customer-entity
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

probes:
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 5
    failureThreshold: 10

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  postgresqlUsername: customer-entity
  existingSecret: postgresql-credentials
  persistence:
    size: 4Gi
    storageClass: rook-ceph-block

applicationConfig:
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
  openapi:
    title: Customer Entity
    description: Customer Entity API
    version: 1.0.0
    security:
      scheme: client-credentials
      authorization-url: https://qwyck.eu.auth0.com/oauth/auth
      refresh-url: https://qwyck.eu.auth0.com/oauth/token
      token-url: https://qwyck.eu.auth0.com/oauth/token
      scopes: CUSTOMER_READ,CUSTOMER_WRITE
    servers:
        - url: http://ms-customer-entity.prod
          description: Customer-Entity internal service
  spring:
    datasource:
      url: jdbc:postgresql://ms-customer-entity-postgresql.prod:5432/postgres
      username: customer-entity
