replicaCount: 1

image:
  tag: 1.0.3
  repository: jrmcdonald/techbyte-demo
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ambassador:
  enabled: true
  mappings:
    app:
      prefix: /techbyte-demo
      service: http://techbyte-demo

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

secrets:
  mountNamedSecret: false

probes:
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 5
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    periodSeconds: 3
    failureThreshold: 8

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

applicationConfig:
  management:
    endpoints:
      web:
        exposure:
          include: health,info
  app:
    name: World
    goodbye: false
