name: lint

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '*/*'

jobs:
  lint:

    if: contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: git fetch --prune --unshallow

      - name: Lint
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: lint

      - name: Kind
        uses: helm/kind-action@v1.0.0-alpha.3
        if: steps.lint.outputs.changed == 'true'

      - name: Test
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: install