name: lint

on:
  push:
    branches:
      - '*'
      - '*/*'
  pull_request:
    branches:
      - '*'
      - '*/*'

jobs:
  lint:

    if: contains(toJson(github.event.commits), '[skip ci]') == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1
        with:
          version: '3.1.2'

      - name: Lint
        run: helm lint charts/*